os: linux
language: python
python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - nightly
  - pypy3.5-6.0
env: TOXENV=py,codecov

install:
  - pip install tox

script:
  - tox
notifications:
  email: false